export const siteData = {
  zh: {
    name: "杨耀鹏",
    brandMark: "YYP",
    heroLineOne: "YAO",
    heroLineTwo: "PENG",
    role: "智能软件工程研究者",
    intro: "南京大学软件工程博士生，研究大模型如何理解、生成并自主维护软件。",
    about:
      "我关注智能软件工程，尤其是 LLM for Coding、自动程序修复与自主工作智能体。我希望把大模型的训练、推理和工具使用能力放进真实的软件开发流程，让它们能够理解代码库、定位问题、生成可靠修复，并与人协作完成更长程的任务。",
    focus: [
      { index: "01", title: "LLM for Coding", detail: "代码生成、理解与仓库级推理" },
      { index: "02", title: "自动程序修复", detail: "缺陷定位、补丁生成与评估" },
      { index: "03", title: "自主工作智能体", detail: "GUI、CLI 与 Computer-use Agent" },
    ],
    facts: [
      { value: "2", label: "篇 ACM TOSEM 论文" },
      { value: "124", label: "项 APR 研究系统梳理" },
      { value: "29", label: "个 GitHub 公开仓库" },
      { value: "3", label: "段计算机教育经历" },
    ],
    timeline: [
      {
        period: "2025.09 - 至今",
        title: "软件工程 · 博士",
        place: "南京大学软件学院 · 南京",
        description: "继续研究智能软件工程、代码大模型和自主工作智能体，关注模型在真实软件仓库与长程任务中的可靠性。",
        tags: ["Ph.D.", "Intelligent SE", "Agents"],
      },
      {
        period: "2023.09 - 2025.06",
        title: "软件工程 · 硕士",
        place: "南京大学软件学院 · 南京",
        description: "围绕自动程序修复、LLM 补丁生成和自然语言修复建议开展研究，完成两项 TOSEM 论文工作及硕士毕业设计。",
        tags: ["M.Eng.", "APR", "LLM4Code"],
      },
      {
        period: "2018.09 - 2022.06",
        title: "计算机科学与技术 · 学士",
        place: "江南大学人工智能与计算机学院 · 无锡",
        description: "建立计算机科学、软件开发与人工智能基础，参与省级优秀大学生创新项目并担任校级社团社长。",
        tags: ["B.Eng.", "Computer Science", "Leadership"],
      },
    ],
    work: [
      {
        number: "01",
        type: "第一作者 · ACM TOSEM",
        title: "Patch Generation in APR",
        summary: "从 LLM 使用方式与 APR 领域信息两个视角系统梳理 124 项研究，建立任务形式、使用技术、推理策略和输入策略的分析框架，并讨论仓库级修复与推理时扩展。",
        meta: "2025 · DOI 10.1145/3764584",
        link: "https://dl.acm.org/doi/10.1145/3764584",
        accent: "#ff5c35",
      },
      {
        number: "02",
        type: "第二作者 · ACM TOSEM",
        title: "IMPACT",
        summary: "面向多来源、多类别自承认技术债构建检测与分类流水线。主要完成 MT-MoE-BERT 检测模型，以及基于 Llama-Factory 和 LoRA 的 GLM-9B 分类模型训练。",
        meta: "2025 · DOI 10.1145/3747180",
        link: "https://github.com/yepYoung/SATD-IMPACT",
        accent: "#2e6cff",
      },
      {
        number: "03",
        type: "硕士毕业设计",
        title: "Natural Language Repair Suggestions",
        summary: "探索以高质量自然语言修复建议辅助开发者理解缺陷。构建缺陷程序与建议数据集，使用偏好对齐训练 CodeLlama-7B，并结合 RAG、Few-shot 与结构化评估代理。",
        meta: "2025 · LLM Alignment / RAG",
        link: "",
        accent: "#8b5cf6",
      },
      {
        number: "04",
        type: "南京大学 LipLab × 华为",
        title: "Self-enhanced APR Generalization",
        summary: "比较双模型与 Agent 架构在不同基准上的自增强效果，分析模型记忆与泛化之间的关系，并验证外部领域信息对修复策略的重要性。",
        meta: "2024 · Industry Research",
        link: "",
        accent: "#16a36a",
      },
    ],
    principles: [
      { number: "01", title: "代码大模型", text: "模型预训练、监督微调、偏好对齐、RAG、推理与 Agent 系统。" },
      { number: "02", title: "研究与实验", text: "自动程序修复、软件仓库分析、实验设计、基准评测与论文写作。" },
      { number: "03", title: "工程能力", text: "Python、Java、PyTorch、Linux，以及常用机器学习和软件工程工具链。" },
      { number: "04", title: "全栈开发", text: "Spring、FastAPI、MySQL、Redis 与 Flutter，能够完成从模型到应用的交付。" },
      { number: "05", title: "奖项与经历", text: "CET-6、国家励志奖学金、学业奖学金二等奖、省级优秀大创项目。" },
    ],
    contacts: [
      { label: "Email", value: "yepyoung2001@gmail.com", href: "mailto:yepyoung2001@gmail.com" },
      { label: "Email · CN", value: "2063569268@qq.com", href: "mailto:2063569268@qq.com" },
      { label: "GitHub", value: "github.com/yepYoung", href: "https://github.com/yepYoung" },
      { label: "ACM", value: "Yaopeng Yang · Author Profile", href: "https://dl.acm.org/profile/99661654803" },
    ],
  },
  en: {
    name: "Yaopeng Yang",
    brandMark: "YYP",
    heroLineOne: "YAO",
    heroLineTwo: "PENG",
    role: "Intelligent Software Engineering Researcher",
    intro: "Ph.D. student at Nanjing University, studying how language models can understand, generate, and autonomously maintain software.",
    about:
      "My research centers on intelligent software engineering, particularly LLMs for coding, automated program repair, and autonomous cowork agents. I bring model training, inference, and tool use into real development workflows, aiming for systems that can understand repositories, locate defects, produce dependable repairs, and collaborate with people on long-horizon tasks.",
    focus: [
      { index: "01", title: "LLMs for Coding", detail: "Code generation, understanding, and repository reasoning" },
      { index: "02", title: "Program Repair", detail: "Fault localization, patch generation, and evaluation" },
      { index: "03", title: "Cowork Agents", detail: "GUI, CLI, and computer-use agents" },
    ],
    facts: [
      { value: "2", label: "ACM TOSEM papers" },
      { value: "124", label: "APR studies reviewed" },
      { value: "29", label: "Public GitHub repositories" },
      { value: "3", label: "Computer science degrees" },
    ],
    timeline: [
      {
        period: "Sep 2025 - Present",
        title: "Ph.D. in Software Engineering",
        place: "Software Institute, Nanjing University · Nanjing",
        description: "Researching intelligent software engineering, code language models, and autonomous cowork agents, with an emphasis on reliability in real repositories and long-horizon tasks.",
        tags: ["Ph.D.", "Intelligent SE", "Agents"],
      },
      {
        period: "Sep 2023 - Jun 2025",
        title: "M.Eng. in Software Engineering",
        place: "Software Institute, Nanjing University · Nanjing",
        description: "Worked on automated program repair, LLM-based patch generation, and natural-language repair suggestions, contributing to two TOSEM papers and a master's thesis project.",
        tags: ["M.Eng.", "APR", "LLM4Code"],
      },
      {
        period: "Sep 2018 - Jun 2022",
        title: "B.Eng. in Computer Science and Technology",
        place: "School of Artificial Intelligence and Computer Science, Jiangnan University · Wuxi",
        description: "Built foundations in computer science, software development, and AI; joined an outstanding provincial innovation project and led a university student organization.",
        tags: ["B.Eng.", "Computer Science", "Leadership"],
      },
    ],
    work: [
      {
        number: "01",
        type: "First Author · ACM TOSEM",
        title: "Patch Generation in APR",
        summary: "A review of 124 studies through two lenses: how LLMs are used and how APR-specific information is incorporated. The work covers task formulation, techniques, inference strategies, inputs, repository-level repair, and inference-time scaling.",
        meta: "2025 · DOI 10.1145/3764584",
        link: "https://dl.acm.org/doi/10.1145/3764584",
        accent: "#ff5c35",
      },
      {
        number: "02",
        type: "Second Author · ACM TOSEM",
        title: "IMPACT",
        summary: "A pipeline for detecting and classifying self-admitted technical debt across sources and categories. My main contributions include MT-MoE-BERT and LoRA fine-tuning of GLM-9B with Llama-Factory.",
        meta: "2025 · DOI 10.1145/3747180",
        link: "https://github.com/yepYoung/SATD-IMPACT",
        accent: "#2e6cff",
      },
      {
        number: "03",
        type: "Master's Thesis Project",
        title: "Natural Language Repair Suggestions",
        summary: "A study of high-quality natural-language suggestions that help developers understand software defects. It combines preference alignment for CodeLlama-7B, RAG, few-shot inference, and a structured evaluation agent.",
        meta: "2025 · LLM Alignment / RAG",
        link: "",
        accent: "#8b5cf6",
      },
      {
        number: "04",
        type: "NJU LipLab × Huawei",
        title: "Self-enhanced APR Generalization",
        summary: "A comparison of dual-model and agent architectures across benchmarks, examining the relationship between memorization and self-enhancement while showing the value of external domain information.",
        meta: "2024 · Industry Research",
        link: "",
        accent: "#16a36a",
      },
    ],
    principles: [
      { number: "01", title: "Code language models", text: "Pretraining, supervised fine-tuning, preference alignment, RAG, inference, and agent systems." },
      { number: "02", title: "Research & evaluation", text: "Program repair, repository analysis, experimental design, benchmarks, and academic writing." },
      { number: "03", title: "Engineering", text: "Python, Java, PyTorch, Linux, and common machine-learning and software-engineering toolchains." },
      { number: "04", title: "Full-stack development", text: "Spring, FastAPI, MySQL, Redis, and Flutter, covering delivery from models to applications." },
      { number: "05", title: "Awards & activities", text: "CET-6, National Encouragement Scholarship, academic scholarship, and an outstanding provincial innovation project." },
    ],
    contacts: [
      { label: "Email", value: "yepyoung2001@gmail.com", href: "mailto:yepyoung2001@gmail.com" },
      { label: "Email · CN", value: "2063569268@qq.com", href: "mailto:2063569268@qq.com" },
      { label: "GitHub", value: "github.com/yepYoung", href: "https://github.com/yepYoung" },
      { label: "ACM", value: "Yaopeng Yang · Author Profile", href: "https://dl.acm.org/profile/99661654803" },
    ],
  },
};

export const interfaceText = {
  zh: {
    navAbout: "关于",
    navExperience: "教育",
    navWork: "研究",
    navContact: "联系",
    talk: "联系我",
    availability: "智能软件工程 · 南京",
    focusLabel: "研究方向",
    focusTitle: "让大模型成为可靠的软件工程协作者",
    scroll: "向下浏览",
    aboutLabel: "关于我",
    experienceLabel: "教育经历",
    experienceTitle: "从计算机科学到智能软件工程",
    experienceHint: "目前在南京大学软件学院攻读博士学位。",
    workLabel: "精选研究",
    workTitle: "论文、系统与研究项目",
    workHint: "围绕程序修复、技术债与代码大模型展开。",
    principlesLabel: "能力与背景",
    principlesTitle: "研究模型，也构建完整系统。",
    contactLabel: "保持联系",
    contactTitle: "讨论研究、工程或合作机会。",
    contactBody: "欢迎通过邮件联系。手机号与精确出生信息不在公开页面展示。",
    footerText: "南京 · 中国",
    openWork: "查看详情",
  },
  en: {
    navAbout: "About",
    navExperience: "Education",
    navWork: "Research",
    navContact: "Contact",
    talk: "Contact me",
    availability: "Intelligent Software Engineering · Nanjing",
    focusLabel: "Research focus",
    focusTitle: "Making language models dependable software engineering collaborators",
    scroll: "Scroll to explore",
    aboutLabel: "About me",
    experienceLabel: "Education",
    experienceTitle: "From computer science to intelligent software engineering",
    experienceHint: "Currently pursuing a Ph.D. at the Software Institute of Nanjing University.",
    workLabel: "Selected research",
    workTitle: "Papers, systems, and research projects",
    workHint: "Work spanning program repair, technical debt, and code language models.",
    principlesLabel: "Capabilities",
    principlesTitle: "Researching models and building complete systems.",
    contactLabel: "Get in touch",
    contactTitle: "Let's discuss research, engineering, or collaboration.",
    contactBody: "Email is the best way to reach me. My phone number and full birth date are kept off the public site.",
    footerText: "Nanjing · China",
    openWork: "View details",
  },
};
