export const siteData = {
  zh: {
    name: "杨耀鹏",
    brandMark: "YYP",
    heroLineOne: "YAO-PENG",
    heroLineTwo: "YANG",
    role: "我是 Yao-Peng Yang（杨耀鹏）。",
    intro: "我目前是南京大学软件学院软件工程方向的一年级博士生，研究兴趣集中在面向软件工程的人工智能技术，尤其是 AI for Coding、软件工程大模型、程序修复、仓库级推理和自主编码智能体。如果你对我的研究或项目感兴趣，欢迎联系与合作。邮箱：602025320022@smail.nju.edu.cn。",
    about:
      "我的研究关注智能软件工程，尤其是 AI for Coding、软件工程大模型、自动程序修复与自主协作智能体。我希望把模型训练、推理和工具使用能力带入真实软件开发流程，让智能系统能够理解代码库、定位缺陷、生成可靠修复，并与人协作完成更长程的任务。",
    focus: [
      { index: "01", title: "AI for Coding", detail: "代码生成、软件工程问题解决、面向代码的强化学习" },
      { index: "02", title: "LLMs for SE", detail: "程序修复、补丁生成" },
      { index: "03", title: "协作智能体", detail: "Computer-use Agent、GUI Agent、CLI/SWE Agent" },
    ],
    facts: [
      { value: "2", label: "篇 ACM TOSEM 论文" },
      { value: "124", label: "项 APR 研究系统梳理" },
      { value: "30", label: "个 GitHub 公开仓库" },
      { value: "3", label: "段计算机教育经历" },
    ],
    timeline: [
      {
        period: "2025.09 - 至今",
        title: "软件工程 · 博士生",
        place: "南京大学软件学院 LipLab · 南京 · 中国",
        description: "研究智能软件工程与自主协作智能体。<br>导师：骆斌教授、李传艺助理教授。",
        tags: ["Ph.D.", "Intelligent SE", "Cowork Agents"],
      },
      {
        period: "2023.09 - 2025.06",
        title: "软件工程 · 硕士",
        place: "南京大学软件学院 LipLab · 南京 · 中国",
        description: "围绕自动程序修复、基于大模型的补丁生成和技术债检测开展研究。<br>导师：葛季栋教授。",
        tags: ["M.Eng.", "APR", "LLM4Code"],
      },
      {
        period: "2018.09 - 2022.06",
        title: "计算机科学与技术 · 学士",
        place: "江南大学人工智能与计算机学院 · 无锡 · 中国",
        description: "建立计算机科学、软件开发和人工智能基础；主持省级优秀大学生创新项目，基于大数据技术和推荐算法匹配赞助企业与公益组织。",
        tags: ["B.Eng.", "Foundations", "Leadership"],
      },
    ],
    news: [
      {
        date: "即将发布",
        tag: "预印本",
        title: "WANDER: Bridging Human Workflow and Automation Computer Usage via Naturalistic Demonstrations and Enhanced Retrieval",
        summary: "WANDER 即将在 arXiv 发布，并计划投稿 AAAI。它面向 GUI Agent 的一个核心矛盾：真实用户操作轨迹包含宝贵的过程经验，却常常伴随冗余、混乱甚至误导性的动作。WANDER 基于操作单元和“意图-状态转移”的双重检索，从自然操作示范中检索并复用与任务相关的人类经验，弥补模型在特定操作中的知识和推理不足，同时削弱无效动作与噪声对智能体决策的负面影响。",
        linkLabel: "arXiv 即将发布",
        link: "",
        accent: "#ff7a2f",
      },
      {
        date: "2026.06",
        tag: "审稿中",
        title: "Understand before Solving via Building an Issue Guidance Model",
        summary: "投稿至 IEEE Transactions on Software Engineering（TSE），目前处于审稿中。现有 SWE-bots 常依赖更强模型或更长的测试时推理，容易带来无引导搜索、难以审阅的决策过程和边际收益下降。该工作训练 Issue Guidance Model，在生成补丁前先预测根因并给出可执行修复建议，使问题解决过程更可审阅，也更贴近真实修复意图。在 SWE-bench Verified 上，结合 mini-SWE-agent 与 DeepSeek-V3.2 Reasoner，将通过率从 60.00% 提升到 65.80%，绝对提升 5.80 个百分点。",
        linkLabel: "",
        link: "",
        accent: "#8b5cf6",
      },
      {
        date: "2026.01",
        tag: "已撤稿",
        title: "Understand before Solving via Building an Issue Guidance Model",
        summary: "该工作的 International Conference on Machine Learning（ICML）投稿版本已由我主动撤稿。OpenReview 页面保留了该版本的官方审稿意见。",
        linkLabel: "审稿意见",
        link: "https://openreview.net/forum?id=LbbpiTiYMo&invitationId=ICML.cc%2F2026%2FConference%2FSubmission29560%2FOfficial_Review1%2F-%2FRebuttal&noteId=PbeALwdlLP&referrer=%5BTasks%5D%28%2Ftasks%29",
        accent: "#2e6cff",
      },
    ],
    work: [
      {
        type: "期刊论文",
        title: "Patch Generation in APR: A Survey from the Perspectives of Utilizing LLMs and Using APR-Specific Information",
        date: "2025.08",
        venue: "ACM Transactions on Software Engineering and Methodology（TOSEM）",
        authors: "Yaopeng Yang, Chuanyi Li, Zhifeng Han, Rui Li, Kui Xu, Qingyuan Li, Wenkang Zhong, Zongwen Shen, Zhiwei Fei, Jidong Ge, Bin Luo",
        affiliations: "State Key Laboratory for Novel Software Technology, Nanjing University, China; China Mobile, China",
        summary: "系统梳理 124 项自动程序修复研究，从大模型使用方式和 APR 领域信息利用两个视角分析补丁生成，覆盖任务形式、技术路线、推理策略、输入构造、仓库级修复与推理时扩展。",
        link: "https://dl.acm.org/doi/10.1145/3764584",
        accent: "#ff5c35",
      },
      {
        type: "期刊论文",
        title: "IMPACT: Identifying and Classifying Multiple Sourced and Categorized Self-Admitted Technical Debts",
        date: "2026.03",
        venue: "ACM Transactions on Software Engineering and Methodology（TOSEM）",
        authors: "Qingyuan Li, Zhixin Yin, Yaopeng Yang, Chuanyi Li, Zongwen Shen, Jidong Ge, Wenkang Zhong, Bin Luo, Vincent Ng",
        affiliations: "National Key Laboratory for Novel Software Technology, Nanjing University, Nanjing, China; Human Language Technology Research Institute, The University of Texas at Dallas, Richardson, Texas, USA",
        summary: "面向多来源、多类别自承认技术债构建检测与分类流程。我的主要贡献包括 MT-MoE-BERT 检测模型，以及基于 Llama-Factory 和 LoRA 的 GLM-9B 分类模型微调。",
        link: "https://github.com/yepYoung/SATD-IMPACT",
        accent: "#2e6cff",
      },
    ],
    projects: [
      {
        type: "项目",
        title: "Ambler",
        summary: "托管在 GitHub 上的个人研究与工程项目，延续我对智能体工作流、编码工具和实用 AI 系统的探索。该项目早于同期的 OpenClaw。",
        meta: "GitHub 仓库",
        link: "https://github.com/yepYoung/Ambler",
        accent: "#8b5cf6",
      },
      {
        type: "实习合作",
        title: "NJU LipLab × Huawei Collaboration",
        summary: "围绕自动程序修复、自增强修复泛化，以及基于智能体的修复工作流开展的产业合作研究。",
        meta: "产业研究 · 华为",
        link: "",
        accent: "#2e6cff",
      },
      {
        type: "贡献",
        title: "AI-Code Compass",
        summary: "参与建设面向 AI 编码工具、代码智能体和相关生态知识的公开指南，帮助读者更高效地探索和比较不同工具。",
        meta: "指南贡献",
        link: "https://yepyoung.github.io/aicode-compass/",
        accent: "#16a36a",
      },
      {
        type: "开源",
        title: "30 个 GitHub 公开仓库",
        summary: "公开仓库覆盖软件工程研究、编码智能体、AI 工具、全栈原型和技术写作等方向。",
        meta: "GitHub · yepYoung",
        link: "https://github.com/yepYoung?tab=repositories",
        accent: "#ff5c35",
      },
    ],
    principles: [
      { number: "01", title: "代码大模型", text: "预训练、监督微调、偏好对齐、RAG、推理与智能体系统。" },
      { number: "02", title: "研究与评估", text: "程序修复、仓库分析、实验设计、基准评测和论文写作。" },
      { number: "03", title: "工程能力", text: "Python、Java、PyTorch、Linux，以及常用机器学习和软件工程工具链。" },
      { number: "04", title: "全栈开发", text: "Spring、FastAPI、MySQL、Redis 和 Flutter，覆盖从模型能力到应用原型的交付。" },
      { number: "05", title: "奖项与经历", text: "CET-6、国家励志奖学金、学业奖学金二等奖、省级优秀大创项目。" },
    ],
    contacts: [
      { label: "Email", value: "602025320022@smail.nju.edu.cn", href: "mailto:602025320022@smail.nju.edu.cn" },
      { label: "GitHub", value: "github.com/yepYoung", href: "https://github.com/yepYoung" },
      { label: "ACM", value: "Yaopeng Yang · Author Profile", href: "https://dl.acm.org/profile/99661654803" },
    ],
  },
  en: {
    name: "Yaopeng Yang",
    brandMark: "YYP",
    heroLineOne: "YAO-PENG",
    heroLineTwo: "YANG",
    role: "Here is Yao-Peng Yang (杨耀鹏).",
    intro: "I am currently a first-year Ph.D. student in Software Engineering at the Software Institute, Nanjing University. I received my master's degree from Nanjing University in 2025 and my bachelor's degree in Computer Science and Technology from Jiangnan University in 2022. My research interests center on artificial intelligence techniques for software engineering, especially AI for coding, LLMs for software engineering, program repair, repository-level reasoning, and autonomous coding agents. If you are interested in any aspect of my work, I would love to chat and collaborate. Please email me at 602025320022@smail.nju.edu.cn.",
    about:
      "My research centers on intelligent software engineering, particularly LLMs for coding, automated program repair, and autonomous cowork agents. I bring model training, inference, and tool use into real development workflows, aiming for systems that can understand repositories, locate defects, produce dependable repairs, and collaborate with people on long-horizon tasks.",
    focus: [
      { index: "01", title: "AI for Coding", detail: "Code Generation, SWE Issue Resolution, RL for Code" },
      { index: "02", title: "LLMs for SE", detail: "Program Repair, patch generation" },
      { index: "03", title: "Cowork Agents", detail: "Computer-use Agent, GUI Agent, CLI/SWE Agent" },
    ],
    facts: [
      { value: "2", label: "ACM TOSEM papers" },
      { value: "124", label: "APR studies reviewed" },
      { value: "30", label: "Public GitHub repositories" },
      { value: "3", label: "Computer science degrees" },
    ],
    timeline: [
      {
        period: "Sep 2025 - Present",
        title: "Ph.D. Candidate - Software Engineering",
        place: "Liplab, Software Institute, Nanjing University · Nanjing · China",
        description: "Researching intelligent software engineering and autonomous cowork agents...<br>Advisors: Prof. Bin Luo and Assistant Prof. Chuanyi Li.",
        tags: ["Ph.D.", "Intelligent SE", "Cowork Agents"],
      },
      {
        period: "Sep 2023 - Jun 2025",
        title: "M.Eng. - Software Engineering",
        place: "Liplab, Software Institute, Nanjing University · Nanjing · China",
        description: "Worked on automated program repair, LLM-based patch generation, and detection of technical debt. Advisor: Prof. Jidong Ge.",
        tags: ["M.Eng.", "APR", "LLM4Code"],
      },
      {
        period: "Sep 2018 - Jun 2022",
        title: "B.Eng. - Computer Science and Technology",
        place: "Institute of Artificial Intelligence and Computer Science, Jiangnan University · Wuxi · China",
        description: "Built foundations in computer science, software development, and AI; led an outstanding provincial innovation project that matched sponsoring companies with non-profit organizations using big data technology and recommendation algorithms.",
        tags: ["B.Eng.", "Foundations", "Leadership"],
      },
    ],
    news: [
      {
        date: "Coming soon",
        tag: "Preprint",
        title: "WANDER: Bridging Human Workflow and Automation Computer Usage via Naturalistic Demonstrations and Enhanced Retrieval",
        summary: "WANDER will be released on arXiv soon, with a planned AAAI submission. It addresses a core tension in GUI agents: human demonstrations contain valuable procedural experience, but real user traces are often noisy, redundant, and even misleading. WANDER uses dual retrieval over operation units and intent-state transitions to recover task-relevant human experience, compensating for the agent's missing knowledge and reasoning while filtering out confusing or ineffective actions.",
        linkLabel: "arXiv coming soon",
        link: "",
        accent: "#ff7a2f",
      },
      {
        date: "Jun 2026",
        tag: "Under Review",
        title: "Understand before Solving via Building an Issue Guidance Model",
        summary: "Under review at IEEE Transactions on Software Engineering (TSE). Current SWE-bots often rely on stronger models or longer test-time reasoning, yet this can lead to unguided search and hard-to-review decisions with diminishing returns. This work builds an issue guidance model that first generates root causes and actionable repair suggestions, making issue solving more reviewable and better aligned with repair intent. With mini-SWE-agent and DeepSeek-V3.2 Reasoner on SWE-bench Verified, it improves the pass rate from 60.00% to 65.80% (+5.80 absolute points).",
        linkLabel: "",
        link: "",
        accent: "#8b5cf6",
      },
      {
        date: "Jan 2026",
        tag: "Withdrawn",
        title: "Understand before Solving via Building an Issue Guidance Model",
        summary: "A withdrawn International Conference on Machine Learning (ICML) submission version of the same work. The OpenReview page includes the official review comments from that submission.",
        linkLabel: "Review comments",
        link: "https://openreview.net/forum?id=LbbpiTiYMo&invitationId=ICML.cc%2F2026%2FConference%2FSubmission29560%2FOfficial_Review1%2F-%2FRebuttal&noteId=PbeALwdlLP&referrer=%5BTasks%5D%28%2Ftasks%29",
        accent: "#2e6cff",
      },
    ],
    work: [
      {
        type: "JOURNAL ARTICLE",
        title: "Patch Generation in APR: A Survey from the Perspectives of Utilizing LLMs and Using APR-Specific Information",
        date: "Aug 2025",
        venue: "ACM Transactions on Software Engineering and Methodology",
        authors: "Yaopeng Yang, Chuanyi Li, Zhifeng Han, Rui Li, Kui Xu, Qingyuan Li, Wenkang Zhong, Zongwen Shen, Zhiwei Fei, Jidong Ge, Bin Luo",
        affiliations: "State Key Laboratory for Novel Software Technology, Nanjing University, China; China Mobile, China",
        summary: "A survey of 124 APR studies from two perspectives: how LLMs are used and how APR-specific information is incorporated, covering task formulation, techniques, inference strategies, inputs, repository-level repair, and inference-time scaling.",
        link: "https://dl.acm.org/doi/10.1145/3764584",
        accent: "#ff5c35",
      },
      {
        type: "JOURNAL ARTICLE",
        title: "IMPACT: Identifying and Classifying Multiple Sourced and Categorized Self-Admitted Technical Debts",
        date: "Mar 2026",
        venue: "ACM Transactions on Software Engineering and Methodology",
        authors: "Qingyuan Li, Zhixin Yin, Yaopeng Yang, Chuanyi Li, Zongwen Shen, Jidong Ge, Wenkang Zhong, Bin Luo, Vincent Ng",
        affiliations: "National Key Laboratory for Novel Software Technology, Nanjing University, Nanjing, China; Human Language Technology Research Institute, The University of Texas at Dallas, Richardson, Texas, USA",
        summary: "A pipeline for detecting and classifying self-admitted technical debt across sources and categories. My main contributions include MT-MoE-BERT and LoRA fine-tuning of GLM-9B with Llama-Factory.",
        link: "https://github.com/yepYoung/SATD-IMPACT",
        accent: "#2e6cff",
      },
    ],
    projects: [
      {
        type: "Project",
        title: "Ambler",
        summary: "A personal research and engineering project hosted on GitHub, connected to my ongoing interest in agentic workflows, coding tools, and practical AI systems. The project predates OpenClaw from the same period.",
        meta: "GitHub Repository",
        link: "https://github.com/yepYoung/Ambler",
        accent: "#8b5cf6",
      },
      {
        type: "Internships",
        title: "NJU LipLab × Huawei Collaboration",
        summary: "Industry research collaboration around automated program repair, self-enhanced repair generalization, and the practical behavior of agent-based repair workflows.",
        meta: "Industry Research · Huawei",
        link: "",
        accent: "#2e6cff",
      },
      {
        type: "Contribution",
        title: "AI-Code Compass",
        summary: "A contribution to a public-facing resource that organizes AI coding tools, code agents, and related ecosystem knowledge for easier exploration and comparison.",
        meta: "Guide Contribution",
        link: "https://yepyoung.github.io/aicode-compass/",
        accent: "#16a36a",
      },
      {
        type: "Open Source",
        title: "30 Public GitHub Repositories",
        summary: "A growing collection of public repositories spanning software engineering research, coding agents, AI tooling, full-stack prototypes, and technical writing.",
        meta: "GitHub · yepYoung",
        link: "https://github.com/yepYoung?tab=repositories",
        accent: "#ff5c35",
      },
    ],
    principles: [
      { number: "01", title: "LLMs", text: "Pretraining, supervised fine-tuning, preference alignment, RAG, inference, and agent systems." },
      { number: "02", title: "Research", text: "Program repair, repository analysis, experimental design, benchmarks, and academic writing." },
      { number: "03", title: "Engineering", text: "Python, Java, PyTorch, Linux, and common machine-learning and software-engineering toolchains." },
      { number: "04", title: "Full-stack development", text: "Spring, FastAPI, MySQL, Redis, and Flutter, covering delivery from back-end to front-end." },
      { number: "05", title: "Awards & activities", text: "CET-6, National Encouragement Scholarship, academic scholarship, and an outstanding provincial innovation project." },
    ],
    contacts: [
      { label: "Email", value: "602025320022@smail.nju.edu.cn", href: "mailto:602025320022@smail.nju.edu.cn" },
      { label: "GitHub", value: "github.com/yepYoung", href: "https://github.com/yepYoung" },
      { label: "ACM", value: "Yaopeng Yang · Author Profile", href: "https://dl.acm.org/profile/99661654803" },
    ],
  },
};

export const interfaceText = {
  zh: {
    navAbout: "关于",
    navExperience: "教育",
    navNews: "动态",
    navWork: "论文",
    navProjects: "项目",
    navContact: "联系",
    talk: "联系我",
    availability: "智能软件工程 · 南京",
    focusLabel: "研究方向",
    focusTitle: "让大模型成为可靠的软件工程协作者",
    scroll: "向下浏览",
    aboutLabel: "关于我",
    experienceLabel: "教育经历",
    newsLabel: "动态",
    experienceTitle: "从计算机科学到智能软件工程",
    experienceHint: "目前在南京大学软件学院攻读博士学位。",
    workLabel: "论文发表",
    projectsLabel: "项目",
    workTitle: "论文发表",
    workHint: "围绕程序修复、技术债与代码大模型展开。",
    principlesLabel: "能力",
    principlesTitle: "技能与荣誉。",
    contactLabel: "保持联系",
    contactTitle: "欢迎交流研究、工程或合作机会。",
    contactBody: "邮件是最合适的联系方式，我会尽量及时回复。",
    footerText: "南京 · 中国",
    openWork: "查看详情",
    authorLabel: "作者",
    affiliationLabel: "机构",
  },
  en: {
    navAbout: "About",
    navExperience: "Education",
    navNews: "News",
    navWork: "Publication",
    navProjects: "Projects",
    navContact: "Contact",
    talk: "Contact me",
    availability: "Intelligent Software Engineering · Nanjing",
    focusLabel: "Research focus",
    focusTitle: "Making language models dependable software engineering collaborators",
    scroll: "Scroll to explore",
    aboutLabel: "About me",
    experienceLabel: "Education",
    newsLabel: "News",
    experienceTitle: "From computer science to intelligent software engineering",
    experienceHint: "Currently pursuing a Ph.D. at the Software Institute of Nanjing University.",
    workLabel: "Publication",
    projectsLabel: "Projects",
    workTitle: "Papers, systems, and research projects",
    workHint: "Work spanning program repair, technical debt, and code language models.",
    principlesLabel: "Capabilities",
    principlesTitle: "Skills and Honors.",
    contactLabel: "Get in touch",
    contactTitle: "Let's discuss research, engineering, or collaboration.",
    contactBody: "Email is the best way to reach me. My phone number and full birth date are kept off the public site.",
    footerText: "Nanjing · China",
    openWork: "View details",
    authorLabel: "Authors",
    affiliationLabel: "Affiliations",
  },
};
